spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diszinventory
    username: diszinventory
    password: diszinventory
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE